package xyz.hyperreal.spritz

import org.apache.http.entity.ContentType


object MediaType {

  val table =
    Map(
      "aac" -> ContentType.create( "audio/aac" ),
      "abw" -> ContentType.create( "application/x-abiword" ),
      "arc" -> ContentType.create( "application/octet-stream" ),
      "avi" -> ContentType.create( "video/x-msvideo" ),
      "azw" -> ContentType.create( "application/vnd.amazon.ebook" ),
      "bin" -> ContentType.create( "application/octet-stream" ),
      "bmp" -> ContentType.create( "image/bmp" ),
      "bz" -> ContentType.create( "application/x-bzip" ),
      "bz2" -> ContentType.create( "application/x-bzip2" ),
      "csh" -> ContentType.create( "application/x-csh" ),
      "css" -> ContentType.create( "text/css" ),
      "csv" -> ContentType.create( "text/csv" ),
      "doc" -> ContentType.create( "application/msword" ),
      "docx" -> ContentType.create( "application/vnd.openxmlformats-officedocument.wordprocessingml.document" ),
      "eot" -> ContentType.create( "application/vnd.ms-fontobject" ),
      "epub" -> ContentType.create( "application/epub+zip" ),
      "es" -> ContentType.create( "application/ecmascript" ),
      "gif" -> ContentType.create( "image/gif" ),
      "htm" -> ContentType.create( "text/html" ),
      "html" -> ContentType.create( "text/html" ),
      "ico" -> ContentType.create( "image/x-icon" ),
      "ics" -> ContentType.create( "text/calendar" ),
      "jar" -> ContentType.create( "application/java-archive" ),
      "jpg" -> ContentType.create( "image/jpeg" ),
      "jpg" -> ContentType.create( "image/jpeg" ),
      "js" -> ContentType.create( "application/javascript" ),
      "json" -> ContentType.create( "application/json" ),
      "mid" -> ContentType.create( "audio/midi" ),
      "midi" -> ContentType.create( "audio/midi" ),
      "mpeg" -> ContentType.create( "video/mpeg" ),
      "mpkg" -> ContentType.create( "application/vnd.apple.installer+xml" ),
      "odp" -> ContentType.create( "application/vnd.oasis.opendocument.presentation" ),
      "ods" -> ContentType.create( "application/vnd.oasis.opendocument.spreadsheet" ),
      "odt" -> ContentType.create( "application/vnd.oasis.opendocument.text" ),
      "oga" -> ContentType.create( "audio/ogg" ),
      "ogv" -> ContentType.create( "video/ogg" ),
      "ogx" -> ContentType.create( "application/ogg" ),
      "otf" -> ContentType.create( "font/otf" ),
      "png" -> ContentType.create( "image/png" ),
      "pdf" -> ContentType.create( "application/pdf" ),
      "ppt" -> ContentType.create( "application/vnd.ms-powerpoint" ),
      "pptx" -> ContentType.create( "application/vnd.openxmlformats-officedocument.presentationml.presentation" ),
      "rar" -> ContentType.create( "application/x-rar-compressed" ),
      "rtf" -> ContentType.create( "application/rtf" ),
      "sh" -> ContentType.create( "application/x-sh" ),
      "svg" -> ContentType.create( "image/svg+xml" ),
      "swf" -> ContentType.create( "application/x-shockwave-flash" ),
      "tar" -> ContentType.create( "application/x-tar" ),
      "tif" -> ContentType.create( "image/tiff" ),
      "tiff" -> ContentType.create( "image/tiff" ),
      "ts" -> ContentType.create( "application/typescript" ),
      "ttf" -> ContentType.create( "font/ttf" ),
      "txt" -> ContentType.create( "text/plain" ),
      "vsd" -> ContentType.create( "application/vnd.visio" ),
      "wav" -> ContentType.create( "audio/wav" ),
      "weba" -> ContentType.create( "audio/webm" ),
      "webm" -> ContentType.create( "video/webm" ),
      "webp" -> ContentType.create( "image/webp" ),
      "woff" -> ContentType.create( "font/woff" ),
      "woff2" -> ContentType.create( "font/woff2" ),
      "xhtml" -> ContentType.create( "application/xhtml+xml" ),
      "xls" -> ContentType.create( "application/vnd.ms-excel" ),
      "xlsx" -> ContentType.create( "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" ),
      "xml" -> ContentType.create( "application/xml" ),
      "xul" -> ContentType.create( "application/vnd.mozilla.xul+xml" ),
      "zip" -> ContentType.create( "application/zip" ),
      "3gp" -> ContentType.create( "video/3gpp" ),
      "3g2" -> ContentType.create( "video/3gpp2" ),
      "7z" -> ContentType.create( "application/x-7z-compressed" )
    )
}